export const BACK_HOST = process.env.NEXT_PUBLIC_BACK_HOST as string
export const BACK_PORT = process.env.NEXT_PUBLIC_BACK_PORT as string
export const OFFICIAL_DOLLAR_QUOTATION = Number(process.env.NEXT_PUBLIC_OFFICIAL_DOLLAR_QUOTATION)
export const BLUE_DOLLAR_QUOTATION = Number(process.env.NEXT_PUBLIC_BLUE_DOLLAR_QUOTATION)
export const MEP_DOLLAR_QUOTATION = Number(process.env.NEXT_PUBLIC_MEP_DOLLAR_QUOTATION)
export const CCL_DOLLAR_QUOTATION = Number(process.env.NEXT_PUBLIC_CCL_DOLLAR_QUOTATION)
export const LEDES_DOLLAR_QUOTATION = Number(process.env.NEXT_PUBLIC_LEDES_DOLLAR_QUOTATION)
export const QUOTATIONS = [
  OFFICIAL_DOLLAR_QUOTATION,
  BLUE_DOLLAR_QUOTATION,
  MEP_DOLLAR_QUOTATION,
  CCL_DOLLAR_QUOTATION,
  LEDES_DOLLAR_QUOTATION
]
